
version: '2'
services:
  mongodb:
    image: docker-enp.bin.cloud.barco.com/eis/baseos9-mongo32:1.1.1
    command: --auth
    environment:
      - MONGODB_CONFIG=[{"user":"barco","password":"YjRyYzAsQkNE","dbname":"admin"},{"user":"licenseclient","password":"q3Lf5ASsZc2JyE52","dbname":"licenseclient"},{"user":"tstorage","password":"4s3Ew4RcfxcBbKnZ","dbname":"tstorage"},{"user":"vmmongo","password":"YjRyYzAsQkNE","dbname":"vmapp"}]
    volumes:
      - /dev/db:/data/db
      - /dev/configdb:/data/configdb
    ports:
      - "27017:27017"

  devicemanager:
    image: dockerdev-enp.bin.cloud.barco.com/edp/devicemanager:0.0.1-develop-ba8325aec7-jenkins-52
    environment:
      - mongo_url=mongodb
      - lc_url=licenceclient
      - openfire_url=openfire
    depends_on:
      - mongodb
      - host-agent
    ports:
      - "10087:10087"
      - "8002:8002"

  host-agent:
    image: dockerdev-enp.bin.cloud.barco.com/edp/host-agent:0.0.0-develop-9421fd67f0-jenkins-36
    environment:
      - SYSTEMAPI_URL=$SYSTEMAPI_URI
      - DEBUG_ENABLED=n
    ports:
      - "10080:10080"
      - "8000:8000"
    depends_on:
      - openfire
    volumes:
      - /dev/etc/ecs:/etc/ecs

  openfire:
    image: dockerdev-enp.bin.cloud.barco.com/edp/openfire-broker:0.0.0-develop-db00461085-jenkins-21
    ports:
      - "10090:10090"
      - "10091:10091"
      - "5222:5222"
    environment:
      - mongo_url=mongodb
    depends_on:
      - mongodb

  licenseclient:
    image: docker-enp.bin.cloud.barco.com/eis/licenseclient:0.20.0
    ports:
      - "8081:80"
    environment:
      - LICENSE_CLIENT_PORT=80
      - LICENSE_CLIENT_DB_URI=mongodb://licenseclient:q3Lf5ASsZc2JyE52@mongodb:27017/licenseclient?authSource=admin
      - LICENSE_CLIENT_TS_URI=mongodb://tstorage:4s3Ew4RcfxcBbKnZ@mongodb:27017/tstorage?authSource=admin
      - LICENSE_CLIENT_ENVIRONMENT=dev
      - LICENSE_CLIENT_TEMP_PATH=/tmp
      - LICENSE_MANAGER_URL=
      - LICENSE_CLIENT_ENTITLEMENT_ACTIVATION_OIDC_CONFIG=
    depends_on:
      - mongodb

  systemmanagerui:
    image: dockerdev-enp.bin.cloud.barco.com/edp/systemmanagerui:0.0.0-develop-124dcc99c6-jenkins-25
    environment:
      - SYSTEMAPI_URI=${SYSTEMAPI_URI}/
    depends_on:
      - devicemanager
      - licenseclient
    ports:
      - "4000:4000"
    volumes:
      - /dev/etc/ecs:/etc/ecs

  evmapp:
    image: dockerdev-enp.bin.cloud.barco.com/evm/evmapp:0.0.1-NET0031-1097-04f63d640f-jenkins-10
    ports:
      - "3000:3000"

  postgres:
    image: docker-enp.bin.cloud.barco.com/eis/postgres-barco:0.1.0
    command: postgres
    environment:
      - POSTGRESDB_CONFIG=[{"user":"postgresroot","password":"uZbcDbBV1G","dbname":"admin"},{"user":"keycloak","password":"YlA0N869fk1","dbname":"keycloakdb"}]
    volumes:
      - dbPostgreSql:/var/lib/postgresql/data

  iam:
    image: docker-enp.bin.cloud.barco.com/eis/iam:4.17.0
    environment:
      - KEYCLOAK_LOGLEVEL=DEBUG
      - IAM_POSTGRESDB_URI=jdbc:postgresql://keycloak:YlA0N869fk1@postgres:5432/keycloakdb
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=P94yv2yQfRfi30ebq5XB
      - JWE_KEY="dummy, not working backup"
 
  vm-proxy:
    image: docker-enp.bin.cloud.barco.com/eis/vm-proxy:0.1.1
    ports:
      - "443:443"
    depends_on:
      - iam
      - evmapp
      - devicemanager
      - systemmanagerui

#  nginx-systemapi-docker:
#    image: docker-enp.bin.cloud.barco.com/eis/nginx-systemapi-docker:1.0.0
#    ports:
#      - "80:80"
#    environment:
#      - SYSTEMAPI_URI
volumes:
  dbPostgreSql:
